### ISSUE TITLE
Autocheck 1.0.1 not working with latest version of Complianz (4.6.10)

### ISSUE THREAD

**Issue by disidmarketing** [Really-Simple-Plugins/complianz-gdpr-autocheck#2]
We have noticed that Complianz Autocheck 1.0.1 is not working with latest version of Complianz (4.6.10).

Can you check this please?

Thanks. Best regards from Spain.

**Comment by rlankhorst** [comment]
Hi  @disidmarketing, 

It appears the Tag Manager variation with custom categories wasn't up to date yet in this plugin. I've fixed this, it should work with the new version (1.0.2)

**Comment by disidmarketing** [comment]
Hi @rlankhorst,

Thanks for your effort but for us it's still not working. Any idea of what could be happening?

Thanks.

**Comment by rlankhorst** [comment]
What configuration do you use for the banner? Then I can test with your setup.

**Comment by disidmarketing** [comment]
What do you need exactly from our settings?

This is the export of the settings where we have redacted the company name, phone, address and email (and added the .txt so that we could upload it: [complianz-export.json.txt](https://github.com/Really-Simple-Plugins/complianz-gdpr-autocheck/files/5012363/complianz-export.json.txt)

You can also see the plugin in action on [www.disid.com](https://www.disid.com).

Is this enough?

Thanks for your help.

**Comment by rlankhorst** [comment]
Yes, that should do fine, I’ll try to reproduce the issue with your settings.

**Comment by rlankhorst** [comment]
With your setup it's working for me. I notice there's a jquery error on your page when marketing is not accepted. This might prevent the complianz script from running. The error is caused because the CAOS front-end script is not blocked, while the script it depends on is blocked. 

If you (temporarily) deactivate CAOS, does it start working? Please note that you should test in private mode. 

If this resolves it, adding the following to your functions.php or a mu-plugin should resolve the problem:
```
function custom_caos_add_data_attribute($tag, $handle) {
	if ( 'caos_frontend_script' !== $handle )
		return $tag;

	$classes = COMPLIANZ::$cookie_admin->get_statistics_script_classes();
	$attr = ' class="' . implode( ' ', $classes ) . '" ';

	return str_replace( ' src', " $attr src", $tag );
}
add_filter('script_loader_tag', 'custom_caos_add_data_attribute', 10, 2);
```

**Comment by disidmarketing** [comment]
Hi @rlankhorst,

Thanks for your efforts but it's still not working for us. We created a copy of the website to test and with all other plugins disabled, it still doesn't work.

You can find the staging site here: https://disid.proyectosbeta.com. It's server site protected so that Google doesn't index it. User: test - Pass: 12345

There you can see that it doesn't work for us.

If you need access to the WordPress installation, we can create you a login to this site.

Best regards from Spain.

**Comment by rlankhorst** [comment]
@disidmarketing can you contact us at support@complianz.io?

**Comment by disidmarketing** [comment]
Hi @rlankhorst. I just contacted you at support@complianz.io.

Thanks for your help.

**Comment by disidmarketing** [comment]
Issue solved with the [latest changes](https://github.com/Really-Simple-Plugins/complianz-gdpr-autocheck/commit/aa6e40db3da0dd8af66f32759be774abd5069e77).

Thanks to @rlankhorst for his effort to help us. We are very grateful for his involvement in helping us find a solution.

Best regards from Spain.
